# Generated by Django 3.2.8 on 2023-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cv',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='menu',
            field=models.FileField(blank=True, null=True, upload_to='menu'),
        ),
    ]
