# Generated by Django 3.2.8 on 2023-10-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231001_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='text',
            new_name='heroText',
        ),
    ]
