# Generated by Django 3.2.8 on 2023-10-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_text_userprofile_herotext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='heroText',
            new_name='heroText1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='heroText2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
