# Generated by Django 3.2.8 on 2023-10-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231001_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='heroText3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='heroVideoURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
