# Generated by Django 3.2.8 on 2023-10-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20231001_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('AboutUsText', models.TextField(blank=True, null=True)),
                ('AboutUsContactNumber', models.TextField(blank=True, null=True)),
                ('AboutUsImageBig', models.ImageField(blank=True, null=True, upload_to='AboutUsImages')),
                ('AboutUsImageSmall', models.ImageField(blank=True, null=True, upload_to='AboutUsImages')),
            ],
        ),
    ]
