# Generated by Django 3.2.8 on 2023-10-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
