# Generated by Django 3.2.8 on 2023-10-02 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
