# Generated by Django 3.2.8 on 2023-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_testimonial_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.CheckConstraint(check=models.Q(('stars__gte', 1), ('stars__lt', 5)), name='A value is valid between 1 and 5'),
        ),
    ]
