# Generated by Django 3.2.8 on 2023-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20231002_1439'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testimonial',
            name='A value is valid between 1 and 5',
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.CheckConstraint(check=models.Q(('stars__gte', 1), ('stars__lt', 5)), name='A star value is valid between 1 and 5'),
        ),
    ]
