# Generated by Django 3.2.8 on 2023-10-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_chef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='description',
            new_name='bio',
        ),
    ]
