# Generated by Django 3.2.8 on 2023-10-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_description_chef_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['price'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
