# Generated by Django 3.2.8 on 2023-10-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_event_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='AboutUsContactNumber',
            new_name='VideoURL',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='AboutUsText',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='AboutUsImageBig',
            new_name='image_big',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='AboutUsImageSmall',
            new_name='image_small',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_bottom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_top',
            field=models.TextField(blank=True, null=True),
        ),
    ]
