# Generated by Django 3.2.8 on 2023-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_aboutus_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
