# Generated by Django 3.2.8 on 2023-10-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_aboutus_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Galley',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
