# Generated by Django 3.2.8 on 2023-10-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20231014_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='subject',
            field=models.CharField(default='None', max_length=100, verbose_name='Subject'),
        ),
    ]
