# Generated by Django 3.2.8 on 2023-10-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20231015_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Gallery')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Galley',
            },
        ),
        migrations.DeleteModel(
            name='Galley',
        ),
    ]
