# Generated by Django 3.2.8 on 2023-10-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20231015_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='VideoURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='facebookURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='instagramURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='linkedinURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='twitterURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='heroVideoURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
