# Generated by Django 3.2.8 on 2023-10-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20231015_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='myfacebookURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='myinstagramURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mylinkedinURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mytwitterURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
