# Generated by Django 3.2.8 on 2023-10-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20231016_2312'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testimonial',
            name='A star value is valid between 1 and 5',
        ),
    ]
