# Generated by Django 3.2.8 on 2023-10-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_testimonial_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_booked_for',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='num_people',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time_booked_for',
            new_name='time',
        ),
    ]
