# Generated by Django 3.2.8 on 2023-10-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20231021_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
