# Generated by Django 3.2.8 on 2023-10-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='mywhatsappURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
