# Generated by Django 3.2.8 on 2023-10-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactprofile',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
    ]
