# Generated by Django 3.2.8 on 2023-10-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20231025_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('heroImage', models.ImageField(blank=True, null=True, upload_to='heroImage')),
                ('heroText1', models.TextField(blank=True, null=True)),
                ('heroText2', models.TextField(blank=True, null=True)),
                ('heroText3', models.TextField(blank=True, null=True)),
                ('heroVideoURL', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
