# Generated by Django 3.2.8 on 2023-10-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20231027_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Meta Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Meta description')),
                ('keywords', models.TextField(blank=True, max_length=500, null=True, verbose_name='Meta keywords')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons', verbose_name='Favicon')),
                ('favicon_apple', models.ImageField(blank=True, null=True, upload_to='favicons', verbose_name='Apple touch favicon')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
    ]
